import type { FeatureFlag, MediaItem, Project, ShopProduct, WritingPost } from "./types";

export const projects: Project[] = [
  {
    slug: "site-foundation",
    title: "Almicsen platform foundation",
    subtitle: "A personal web platform built to grow past a portfolio.",
    description:
      "The first version of almicsen.com: public pages, admin scaffolding, CMS-ready models, and room for experiments.",
    longWriteup:
      "This project is the platform itself. V1 keeps the public surface honest and lightweight while preparing for projects, writing, shop links, friends, feature flags, and media wrappers.",
    tags: ["Next.js", "CMS", "Vercel"],
    categories: ["Platform", "Web"],
    date: "2026-05-11",
    status: "IN_PROGRESS",
    visibility: "PUBLISHED",
    featured: true,
    imageUrls: [],
    videoEmbedUrls: [],
    documentUrls: ["/media/pdf"],
    githubUrl: undefined,
    credits: ["almicsen"],
    externalLinks: [{ label: "Media wrapper", href: "/media/video" }],
    scoreMediaSlugs: ["score-sync-demo"],
  },
  {
    slug: "media-wrapper-lab",
    title: "Media wrapper lab",
    subtitle: "Custom shells for PDFs, video embeds, and future managed storage.",
    description:
      "A practical media layer for showing documents and video without pretending GitHub or chat apps are a storage plan.",
    longWriteup:
      "The media wrapper lab keeps public rendering simple while isolating provider details behind CMS metadata. V1 handles external URLs and embeds. Later, the same content model can point at Vercel Blob or another durable media store.",
    tags: ["Media", "PDF", "Video"],
    categories: ["Platform", "Media"],
    date: "2026-05-12",
    status: "IN_PROGRESS",
    visibility: "PUBLISHED",
    featured: true,
    imageUrls: [],
    videoEmbedUrls: ["/media/video"],
    documentUrls: ["/media/pdf"],
    githubUrl: undefined,
    credits: ["almicsen"],
    externalLinks: [
      { label: "PDF wrapper", href: "/media/pdf" },
      { label: "Video wrapper", href: "/media/video" },
    ],
    scoreMediaSlugs: ["score-sync-demo"],
  },
  {
    slug: "creative-system",
    title: "Creative system sketchbook",
    subtitle: "A home for digital experiments that do not fit neatly in a resume.",
    description:
      "A structured place for experiments, prototypes, visuals, code ideas, and strange little web objects.",
    longWriteup:
      "The creative work section can grow into a mixed archive without forcing every piece into a standard case-study template.",
    tags: ["Creative work", "Experiments", "Archive"],
    categories: ["Creative Work"],
    date: "2026-05-11",
    status: "IDEA",
    visibility: "PUBLISHED",
    featured: false,
    imageUrls: [],
    videoEmbedUrls: [],
    documentUrls: [],
    credits: ["almicsen"],
    externalLinks: [],
  },
  {
    slug: "boop-fat-fingers-prototype",
    title: "Boop the Fat Fingers prototype",
    subtitle: "A small original friend-corner interaction, gated by feature flags later.",
    description:
      "A playful mini-widget concept that stays original, toggleable, and separated from the public CMS surface.",
    longWriteup:
      "This prototype keeps the friend-facing idea behind a simple feature-flag boundary. It is listed here as a creative project model, not as a finished public friend-authored feature.",
    tags: ["Friends", "Easter egg", "Interaction"],
    categories: ["Creative Work", "Friends"],
    date: "2026-05-12",
    status: "IDEA",
    visibility: "PUBLISHED",
    featured: false,
    imageUrls: [],
    videoEmbedUrls: [],
    documentUrls: [],
    credits: ["almicsen"],
    externalLinks: [{ label: "Friends corner", href: "/friends" }],
  },
  {
    slug: "unlisted-case-study-draft",
    title: "Unlisted case-study draft",
    subtitle: "A direct-link sample for future previews.",
    description:
      "This record should not appear in public listings, but the visibility state is represented in the model.",
    longWriteup:
      "Unlisted content is useful for review links and previews. The current public listing services exclude it, while direct lookup services can support it later when preview rules are explicit.",
    tags: ["Preview", "CMS"],
    categories: ["Platform"],
    date: "2026-05-12",
    status: "PAUSED",
    visibility: "UNLISTED",
    featured: false,
    imageUrls: [],
    videoEmbedUrls: [],
    documentUrls: [],
    credits: ["almicsen"],
    externalLinks: [],
  },
];

export const writingPosts: WritingPost[] = [
  {
    slug: "notes-from-the-build",
    title: "Notes from the build",
    subtitle: "A quiet starting point for essays, dev logs, and odd internet field notes.",
    body:
      "This is placeholder structured content. Future posts can be drafted, published, unlisted, private, or friend-only without changing the public rendering contract.",
    category: "Dev log",
    tags: ["Platform", "Writing"],
    series: "Almicsen v1",
    chapter: 1,
    visibility: "PUBLISHED",
    publishedAt: "2026-05-11",
    authorName: "almicsen",
  },
  {
    slug: "creative-index",
    title: "Creative index",
    subtitle: "A future table of contents for projects that are more vibe than product.",
    body:
      "Writing should feel personal and direct, with enough structure for filtering, series, and future friend-authored posts.",
    category: "Creative",
    tags: ["Archive", "Creative"],
    visibility: "PUBLISHED",
    publishedAt: "2026-05-11",
    authorName: "almicsen",
  },
  {
    slug: "cms-visibility-states",
    title: "CMS visibility states",
    subtitle: "A note on drafts, private posts, unlisted links, and friend-only pieces.",
    body:
      "The writing model already carries the states needed for moderation and future friend features. Public pages only list published records, while the shape leaves room for safer preview flows later.",
    category: "Site notes",
    tags: ["CMS", "Visibility"],
    series: "Almicsen v1",
    chapter: 2,
    visibility: "PUBLISHED",
    publishedAt: "2026-05-12",
    authorName: "almicsen",
  },
  {
    slug: "friend-post-placeholder",
    title: "Friend post placeholder",
    subtitle: "Future authoring will require moderation before anything public exists.",
    body:
      "This is intentionally private sample data. It proves the author field and friend-only state exist without exposing friend-generated public pages.",
    category: "Friends",
    tags: ["Friends", "Moderation"],
    visibility: "FRIEND_ONLY",
    authorName: "Future friend",
  },
];

export const shopProducts: ShopProduct[] = [
  {
    slug: "external-test-product",
    title: "External shop slot",
    subtitle: "A product card pattern for off-site sellers.",
    description:
      "V1 does not process payments. This card demonstrates the external-purchase flow and third-party checkout warning.",
    imageUrls: [],
    priceDisplay: "Price handled off-site",
    externalPurchaseUrl: "https://example.com",
    sellerName: "Third-party seller",
    status: "ACTIVE",
    visibility: "PUBLISHED",
    tags: ["External link", "Shop"],
    categories: ["Placeholder"],
    featured: true,
  },
  {
    slug: "printful-style-test-slot",
    title: "External print slot",
    subtitle: "A merch-style card that sends checkout somewhere else.",
    description:
      "This product model keeps seller, category, price display, images, and purchase URL separate from any future native commerce system.",
    imageUrls: [],
    priceDisplay: "Seller sets final price",
    externalPurchaseUrl: "https://example.com",
    sellerName: "External print seller",
    status: "ACTIVE",
    visibility: "PUBLISHED",
    tags: ["Print", "External checkout"],
    categories: ["Merch"],
    featured: false,
    previewScoreMediaSlugs: ["score-sync-demo"],
  },
  {
    slug: "sold-out-archive-slot",
    title: "Sold-out archive slot",
    subtitle: "A product record that remains visible without checkout pressure.",
    description:
      "Archived and sold-out states can be shown clearly while checkout still happens off-site when available.",
    imageUrls: [],
    priceDisplay: "Unavailable",
    externalPurchaseUrl: "https://example.com",
    sellerName: "Third-party seller",
    status: "SOLD_OUT",
    visibility: "PUBLISHED",
    tags: ["Archive", "Shop"],
    categories: ["Archive"],
    featured: false,
  },
];

export const mediaItems: MediaItem[] = [
  {
    slug: "score-sync-demo",
    title: "ScoreSync demo score",
    description:
      "A mock score media item for PDF-style pages, audio timeline simulation, and manual Node Frames.",
    kind: "PDF",
    url: "https://example.com/score-sync-demo.pdf",
    provider: "ScoreSync mock",
    visibility: "PUBLISHED",
    score: {
      id: "score-sync-demo",
      isMusicScore: true,
      scoreTitle: "ScoreSync demo score",
      scoreSubtitle: "PDF + audio + manual Node Frames scaffold",
      composer: "almicsen",
      arranger: "ScoreSync Framework",
      instrumentation: "Piano sketch / framework demo",
      difficulty: "Prototype",
      durationLabel: "0:42",
      durationMs: 42000,
      pageCount: 5,
      scorePdfUrl: "https://example.com/score-sync-demo.pdf",
      audioUrl: undefined,
      musicXmlUrl: undefined,
      midiUrl: undefined,
      externalMuseScoreEmbedUrl: undefined,
      preferredScoreEngine: "PDF_AUDIO",
      scoreLayoutMode: "AUTO_SCORE_BOOK",
      firstPageSolo: true,
      pagesPerSpreadAfterFirst: 2,
      autoTurnPages: true,
      showAudioPlayer: true,
      showPageThumbnails: true,
      showFullscreenButton: false,
      showDownloadButton: false,
      downloadPermission: "DISABLED",
      allowExternalOpen: true,
      visibility: "PUBLISHED",
      nodeFrames: [
        {
          id: "score-sync-demo-intro",
          scoreMediaId: "score-sync-demo",
          label: "Intro page",
          startTimeMs: 0,
          endTimeMs: 9000,
          actionType: "TURN_TO_PAGE",
          pageNumber: 1,
          enabled: true,
          createdAt: "2026-05-12",
          updatedAt: "2026-05-12",
        },
        {
          id: "score-sync-demo-a",
          scoreMediaId: "score-sync-demo",
          label: "First spread",
          startTimeMs: 9000,
          endTimeMs: 21000,
          actionType: "TURN_TO_SPREAD",
          spreadIndex: 1,
          enabled: true,
          createdAt: "2026-05-12",
          updatedAt: "2026-05-12",
        },
        {
          id: "score-sync-demo-highlight",
          scoreMediaId: "score-sync-demo",
          label: "Motif callout",
          startTimeMs: 21000,
          endTimeMs: 30000,
          actionType: "HIGHLIGHT_REGION",
          spreadIndex: 1,
          region: { x: 16, y: 28, width: 42, height: 18, unit: "PERCENT" },
          animationDurationMs: 240,
          enabled: true,
          createdAt: "2026-05-12",
          updatedAt: "2026-05-12",
        },
        {
          id: "score-sync-demo-ending",
          scoreMediaId: "score-sync-demo",
          label: "Closing spread",
          startTimeMs: 30000,
          endTimeMs: 42000,
          actionType: "TURN_TO_SPREAD",
          spreadIndex: 2,
          enabled: true,
          createdAt: "2026-05-12",
          updatedAt: "2026-05-12",
        },
      ],
    },
  },
  {
    slug: "sample-pdf-wrapper",
    title: "PDF wrapper sample",
    description:
      "A custom document shell for externally hosted PDFs, with storage and permissions kept out of v1.",
    kind: "PDF",
    url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    provider: "External PDF URL",
    visibility: "PUBLISHED",
  },
  {
    slug: "sample-video-wrapper",
    title: "Video wrapper sample",
    description:
      "A custom shell for a third-party embed, with transcoding and private playback intentionally deferred.",
    kind: "VIDEO",
    url: "https://example.com/video",
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    provider: "External embed",
    visibility: "PUBLISHED",
  },
];

export const featureFlags: FeatureFlag[] = [
  {
    key: "easteregg.boopFatFingers",
    name: "Boop the Fat Fingers",
    description: "Original retro mini-widget for the friends corner.",
    enabled: true,
    visibility: "PUBLISHED",
  },
  {
    key: "friends.corner",
    name: "Corner of Friends",
    description: "Friend-facing placeholder area.",
    enabled: true,
    visibility: "PUBLISHED",
  },
  {
    key: "shop.enabled",
    name: "Shop",
    description: "External-link shop cards.",
    enabled: true,
    visibility: "PUBLISHED",
  },
  {
    key: "media.pdfViewer",
    name: "PDF viewer",
    description: "Custom wrapper for external PDFs.",
    enabled: true,
    visibility: "PUBLISHED",
  },
  {
    key: "media.videoWrapper",
    name: "Video wrapper",
    description: "Custom wrapper for external video.",
    enabled: true,
    visibility: "PUBLISHED",
  },
  {
    key: "media.scoreSync",
    name: "ScoreSync",
    description: "Reusable PDF/audio score viewer framework.",
    enabled: true,
    visibility: "PUBLISHED",
  },
  {
    key: "media.scoreSync.nodeFrames",
    name: "ScoreSync Node Frames",
    description: "Manual time markers for page turns, callouts, and region highlights.",
    enabled: true,
    visibility: "PUBLISHED",
  },
  {
    key: "media.scoreSync.externalMuseScore",
    name: "ScoreSync external MuseScore fallback",
    description: "Controlled external score iframe fallback. Not the core engine.",
    enabled: true,
    visibility: "ADMIN_ONLY",
  },
  {
    key: "media.scoreSync.musicXmlOsmd",
    name: "ScoreSync MusicXML OSMD",
    description: "Future OpenSheetMusicDisplay renderer flag.",
    enabled: false,
    visibility: "ADMIN_ONLY",
  },
  {
    key: "media.scoreSync.meiVerovio",
    name: "ScoreSync MEI Verovio",
    description: "Future Verovio renderer flag.",
    enabled: false,
    visibility: "ADMIN_ONLY",
  },
];
